//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventedmxentites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Room
    {
        public int Room_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Event_Venue { get; set; }
        public string Location_Link { get; set; }
        public string Event_type { get; set; }
        public string Equipment { get; set; }
        public Nullable<int> Seat { get; set; }
        public string Room_Img { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
