//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventedmxentites
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizer
    {
        public int F_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Organizer_Type { get; set; }
        public string Email { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Org_Image { get; set; }
    }
}
