//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventedmxentites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Event
    {
        public int S_Id { get; set; }
        public string S_Event { get; set; }
        public string S_Description { get; set; }
        public System.DateTime S_Sdate { get; set; }
        public System.DateTime S_Edate { get; set; }
        public System.TimeSpan S_Stime { get; set; }
        public System.TimeSpan S_Etime { get; set; }
        public string S_Venue { get; set; }
        public string S_Room { get; set; }
        public string S_Sponsor { get; set; }
        public string S_Organizer { get; set; }
    }
}
