//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventedmxentites
{
    using System;
    using System.Collections.Generic;
    
    public partial class sponcer
    {
        public int S_Id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Description { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Logo { get; set; }
    }
}
