//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventedmxentites
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Mgt
    {
        public int User_Id { get; set; }
        public string User_Type { get; set; }
        public string User_Name { get; set; }
        public long Mobile_Number { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string Person_type { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Updateby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string Per_status { get; set; }
    }
}
